[dosbox]
machine=ega

[cpu]
core=normal
cputype=286
cycles=3300
cycleup=500
cycledown=500

[sblaster]
oplmode=opl2

[autoexec]
mount c d:\
c:
cd ASM\80286\ADVENT~1
MASM GAME, GAME, nul, nul
LINK MAIN+GAME+GRAPHICS+COLLI+RANDOM+KEYBOARD+BINCONV+IO, , nul, nul